# Explore Luxe Lab Parquet Results

This notebook loads every `.parquet` file from a Luxe Lab build output and shows row counts, column types, and sample rows.

**Default run folder:** `data/my-first-run` (change `RUN_DIR` below if you built to a different path).

In [1]:
from pathlib import Path
import json
import html

import duckdb
from IPython.display import HTML, Markdown, display

try:
    import pandas as pd
    HAS_PANDAS = True
except ImportError:
    HAS_PANDAS = False

# Point this at any luxe_lab build output folder
PROJECT_ROOT = Path.cwd().resolve()
if not (PROJECT_ROOT / "luxe_lab").exists() and (PROJECT_ROOT.parent / "luxe_lab").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

RUN_DIR = PROJECT_ROOT / "data" / "my-first-run"
MANIFEST_PATH = RUN_DIR / "manifest.json"
con = duckdb.connect()

print(f"Project root: {PROJECT_ROOT}")
print(f"Run directory: {RUN_DIR}")
print(f"Exists: {RUN_DIR.exists()}")
print(f"Pandas available: {HAS_PANDAS}")


def preview_table(path: Path, limit: int = 10):
    result = con.execute(
        "SELECT * FROM read_parquet(?) LIMIT ?",
        [str(path), limit],
    )
    columns = [col[0] for col in result.description]
    rows = result.fetchall()

    if HAS_PANDAS:
        display(pd.DataFrame(rows, columns=columns))
        return

    table_html = "<table><thead><tr>" + "".join(
        f"<th>{html.escape(str(col))}</th>" for col in columns
    ) + "</tr></thead><tbody>"
    for row in rows:
        table_html += "<tr>" + "".join(
            f"<td>{html.escape('' if value is None else str(value))}</td>" for value in row
        ) + "</tr>"
    table_html += "</tbody></table>"
    display(HTML(table_html))

Project root: C:\Users\visha\Documents\Codex\Projects\luxe-cafe-paid-media-decision-lab
Run directory: C:\Users\visha\Documents\Codex\Projects\luxe-cafe-paid-media-decision-lab\data\my-first-run
Exists: True
Pandas available: True

In [2]:
if MANIFEST_PATH.exists():
    with MANIFEST_PATH.open() as f:
        manifest = json.load(f)

    display(Markdown(
        f"**Status:** `{manifest['status']}`  \n"
        f"**Dataset SHA256:** `{manifest['dataset_sha256'][:16]}…`  \n"
        f"**Report window:** {manifest['config']['report_start']} → {manifest['config']['report_end']}"
    ))
else:
    manifest = None
    print("No manifest.json found — will still list parquet files on disk.")

**Status:** `validated`
**Dataset SHA256:** `a58df509f2034733…`
**Report window:** 2026-05-04 → 2026-08-23

In [3]:
parquet_files = sorted(RUN_DIR.rglob("*.parquet"))
sections = {}

for path in parquet_files:
    section = path.parent.name  # e.g. raw, processed
    sections.setdefault(section, []).append(path)

summary_rows = []
for section, paths in sorted(sections.items()):
    for path in sorted(paths):
        row_count = con.execute(
            "SELECT COUNT(*) FROM read_parquet(?)", [str(path)]
        ).fetchone()[0]
        summary_rows.append({
            "section": section,
            "table": path.stem,
            "rows": row_count,
            "path": str(path.relative_to(PROJECT_ROOT)),
        })

if HAS_PANDAS:
    display(pd.DataFrame(summary_rows))
else:
    display(HTML(
        "<table><thead><tr><th>section</th><th>table</th><th>rows</th><th>path</th></tr></thead><tbody>"
        + "".join(
            f"<tr><td>{r['section']}</td><td>{r['table']}</td><td>{r['rows']}</td><td>{r['path']}</td></tr>"
            for r in summary_rows
        )
        + "</tbody></table>"
    ))

,section,table,rows,path
0,processed,campaign_daily,749,data\my-first-run\processed\campaign_daily.par...
1,processed,order_attribution,1846,data\my-first-run\processed\order_attribution....
2,processed,order_economics,1846,data\my-first-run\processed\order_economics.pa...
3,processed,platform_latest,672,data\my-first-run\processed\platform_latest.pa...
4,processed,reconciliation_daily,112,data\my-first-run\processed\reconciliation_dai...
5,raw,budgets,852,data\my-first-run\raw\budgets.parquet
6,raw,campaigns,6,data\my-first-run\raw\campaigns.parquet
7,raw,costs,152,data\my-first-run\raw\costs.parquet
8,raw,creatives,12,data\my-first-run\raw\creatives.parquet
9,raw,inventory,142,data\my-first-run\raw\inventory.parquet
10,raw,media,1704,data\my-first-run\raw\media.parquet
11,raw,orders,1862,data\my-first-run\raw\orders.parquet
12,raw,platform_snapshots,2736,data\my-first-run\raw\platform_snapshots.parquet
13,raw,promotions,1,data\my-first-run\raw\promotions.parquet
14,raw,purchases,1781,data\my-first-run\raw\purchases.parquet
15,raw,refunds,166,data\my-first-run\raw\refunds.parquet
16,raw,sessions,25034,data\my-first-run\raw\sessions.parquet

## Table previews

Each section below shows the first 10 rows and column dtypes for every parquet file.

In [4]:
PREVIEW_ROWS = 10

for section, paths in sorted(sections.items()):
    display(Markdown(f"### {section}"))

    for path in sorted(paths):
        row_count = con.execute(
            "SELECT COUNT(*) FROM read_parquet(?)", [str(path)]
        ).fetchone()[0]

        display(Markdown(f"#### `{path.stem}` — {row_count:,} rows"))
        preview_table(path, limit=PREVIEW_ROWS)

        if HAS_PANDAS:
            df = con.execute("SELECT * FROM read_parquet(?)", [str(path)]).df()
            display(df.dtypes.to_frame("dtype"))

### processed

#### `campaign_daily` — 749 rows

,report_date,campaign_id,impressions,clicks,spend_cents,media_present,orders,net_revenue_cents,booked_revenue_cents,missing_cost_lines,known_contribution_cents,contribution_before_media_cents,contribution_after_media_cents,business_net_roas,ctr,cpc_usd,planned_spend_cents,pacing_ratio,source_class
0,2026-05-04,C01,844.0,26.0,4940,True,2,119998,119998,0,59058,59058,54118,24.291093,0.030806,1.900000,4180.0,1.181818,derived_result
1,2026-05-04,C02,1206.0,30.0,8100,True,3,119998,179997,0,48988,48988,40888,14.814568,0.024876,2.700000,5940.0,1.363636,derived_result
2,2026-05-04,C03,1332.0,28.0,6440,True,2,59999,119998,0,19459,19459,13019,9.316615,0.021021,2.300000,5060.0,1.272727,derived_result
3,2026-05-04,C04,1204.0,28.0,4760,True,1,53999,53999,0,23703,23703,18943,11.344328,0.023256,1.700000,3740.0,1.272727,derived_result
4,2026-05-04,C05,1387.0,29.0,4640,True,3,179997,179997,0,88587,88587,83947,38.792457,0.020908,1.600000,3520.0,1.318182,derived_result
5,2026-05-04,C06,NaN,27.0,3599,True,1,59999,59999,0,29529,29529,25930,16.671020,NaN,1.332963,5000.0,0.719800,derived_result
6,2026-05-04,UNATTRIBUTED,NaN,NaN,0,False,2,119998,119998,0,59058,59058,59058,NaN,NaN,NaN,NaN,NaN,derived_result
7,2026-05-05,C01,1103.0,24.0,4560,True,3,239996,239996,0,118146,118146,113586,52.630702,0.021759,1.900000,4180.0,1.090909,derived_result
8,2026-05-05,C02,757.0,25.0,6750,True,1,59999,59999,0,29529,29529,22779,8.888741,0.033025,2.700000,5940.0,1.136364,derived_result
9,2026-05-05,C03,1177.0,32.0,7360,True,4,239996,239996,0,118116,118116,110756,32.608152,0.027188,2.300000,5060.0,1.454545,derived_result

                                          dtype
report_date                      datetime64[us]
campaign_id                                 str
impressions                               Int64
clicks                                    Int64
spend_cents                               int64
media_present                              bool
orders                                    int64
net_revenue_cents                         int64
booked_revenue_cents                      int64
missing_cost_lines                        int64
known_contribution_cents                  int64
contribution_before_media_cents           int64
contribution_after_media_cents            int64
business_net_roas                       float64
ctr                                     float64
cpc_usd                                 float64
planned_spend_cents                       Int64
pacing_ratio                            float64
source_class                                str

#### `order_attribution` — 1,846 rows

,order_id,campaign_id,touch_session_id,touch_at,method,source_class
0,O000001,C01,S0000006,2026-04-04 10:13:00-04:00,7-day last observed paid click; reporting allo...,derived_result
1,O000002,C01,S0000007,2026-04-04 16:07:00-04:00,7-day last observed paid click; reporting allo...,derived_result
2,O000003,C02,S0000035,2026-04-04 09:15:00-04:00,7-day last observed paid click; reporting allo...,derived_result
3,O000004,C02,S0000036,2026-04-04 08:55:00-04:00,7-day last observed paid click; reporting allo...,derived_result
4,O000005,C03,S0000049,2026-04-04 15:32:00-04:00,7-day last observed paid click; reporting allo...,derived_result
5,O000006,C03,S0000054,2026-04-04 15:20:00-04:00,7-day last observed paid click; reporting allo...,derived_result
6,O000007,C04,S0000077,2026-04-04 10:37:00-04:00,7-day last observed paid click; reporting allo...,derived_result
7,O000008,UNATTRIBUTED,NaN,NaT,7-day last observed paid click; reporting allo...,derived_result
8,O000009,C05,S0000095,2026-04-04 19:33:00-04:00,7-day last observed paid click; reporting allo...,derived_result
9,O000010,C05,S0000102,2026-04-04 10:45:00-04:00,7-day last observed paid click; reporting allo...,derived_result

                                             dtype
order_id                                       str
campaign_id                                    str
touch_session_id                               str
touch_at          datetime64[us, America/New_York]
method                                         str
source_class                                   str

#### `order_economics` — 1,846 rows

,order_id,line_id,journey_id,customer_id,sku,purchased_at,available_at,status,quantity,report_date,booked_revenue_cents,refunded_cents,net_revenue_cents,net_cogs_cents,fulfillment_cents,net_fee_cents,return_handling_cents,cost_missing,source_class,contribution_before_media_cents
0,O000001,1,J0000006,U0000006,ES601,2026-04-04 10:23:00-04:00,2026-04-04 10:53:00-04:00,fulfilled,1,2026-04-04,59999,0,59999,27000,1700,1770,0,False,derived_result,29529
1,O000002,1,J0000007,U0000005,ES601,2026-04-04 16:17:00-04:00,2026-04-04 16:47:00-04:00,fulfilled,1,2026-04-04,59999,0,59999,27000,1700,1770,0,False,derived_result,29529
2,O000003,1,J0000035,U0000035,ES601,2026-04-04 09:25:00-04:00,2026-04-04 09:55:00-04:00,fulfilled,1,2026-04-04,59999,59999,0,5400,1700,1770,1200,False,derived_result,-10070
3,O000004,1,J0000036,U0000036,ES601,2026-04-04 09:05:00-04:00,2026-04-04 09:35:00-04:00,fulfilled,1,2026-04-04,59999,0,59999,27000,1700,1770,0,False,derived_result,29529
4,O000005,1,J0000049,U0000047,ES601,2026-04-05 15:42:00-04:00,2026-04-05 16:12:00-04:00,fulfilled,1,2026-04-05,59999,59999,0,5400,1700,1770,1200,False,derived_result,-10070
5,O000006,1,J0000053,U0000026,ES601,2026-04-05 15:30:00-04:00,2026-04-05 16:00:00-04:00,fulfilled,1,2026-04-05,59999,0,59999,27000,1700,1770,0,False,derived_result,29529
6,O000007,1,J0000075,U0000023,ES601,2026-04-05 10:47:00-04:00,2026-04-05 11:17:00-04:00,fulfilled,1,2026-04-05,53999,0,53999,27000,1700,1596,0,False,derived_result,23703
7,O000008,1,J0000087,U0000087,ES601,2026-04-14 11:19:00-04:00,2026-04-14 11:49:00-04:00,fulfilled,1,2026-04-14,59999,0,59999,27000,1700,1770,0,False,derived_result,29529
8,O000009,1,J0000091,U0000091,ES601,2026-04-04 19:43:00-04:00,2026-04-04 20:13:00-04:00,fulfilled,1,2026-04-04,59999,0,59999,27000,1700,1770,0,False,derived_result,29529
9,O000010,1,J0000098,U0000098,ES601,2026-04-04 10:55:00-04:00,2026-04-04 11:25:00-04:00,fulfilled,1,2026-04-04,59999,0,59999,27000,1700,1770,0,False,derived_result,29529

                                                            dtype
order_id                                                      str
line_id                                                       str
journey_id                                                    str
customer_id                                                   str
sku                                                           str
purchased_at                     datetime64[us, America/New_York]
available_at                     datetime64[us, America/New_York]
status                                                        str
quantity                                                    int32
report_date                                        datetime64[us]
booked_revenue_cents                                        int64
refunded_cents                                              int64
net_revenue_cents                                           int64
net_cogs_cents                                              int64
fulfillment_cents                                           int64
net_fee_cents                                               int64
return_handling_cents                                       int64
cost_missing                                                 bool
source_class                                                  str
contribution_before_media_cents                             int64

#### `platform_latest` — 672 rows

,channel,campaign_id,report_date,snapshot_at,conversions,revenue_cents,date_basis,revenue_basis,source_class
0,affiliate,C06,2026-05-04,2026-05-11 06:00:00-04:00,1,59999,purchase_date,net_of_discount_before_refunds,synthetic_observation
1,affiliate,C06,2026-05-05,2026-05-12 06:00:00-04:00,1,59999,purchase_date,net_of_discount_before_refunds,synthetic_observation
2,affiliate,C06,2026-05-06,2026-05-13 06:00:00-04:00,5,299995,purchase_date,net_of_discount_before_refunds,synthetic_observation
3,affiliate,C06,2026-05-07,2026-05-14 06:00:00-04:00,2,119998,purchase_date,net_of_discount_before_refunds,synthetic_observation
4,affiliate,C06,2026-05-08,2026-05-15 06:00:00-04:00,6,359994,purchase_date,net_of_discount_before_refunds,synthetic_observation
5,affiliate,C06,2026-05-09,2026-05-16 06:00:00-04:00,1,59999,purchase_date,net_of_discount_before_refunds,synthetic_observation
6,affiliate,C06,2026-05-10,2026-05-17 06:00:00-04:00,2,119998,purchase_date,net_of_discount_before_refunds,synthetic_observation
7,affiliate,C06,2026-05-11,2026-05-18 06:00:00-04:00,4,239996,purchase_date,net_of_discount_before_refunds,synthetic_observation
8,affiliate,C06,2026-05-12,2026-05-19 06:00:00-04:00,0,0,purchase_date,net_of_discount_before_refunds,synthetic_observation
9,affiliate,C06,2026-05-13,2026-05-20 06:00:00-04:00,2,119998,purchase_date,net_of_discount_before_refunds,synthetic_observation

                                          dtype
channel                                     str
campaign_id                                 str
report_date                      datetime64[us]
snapshot_at    datetime64[us, America/New_York]
conversions                               int64
revenue_cents                             int64
date_basis                                  str
revenue_basis                               str
source_class                                str

#### `reconciliation_daily` — 112 rows

,report_date,commerce_orders,commerce_booked_cents,commerce_net_cents,tracked_orders,untracked_orders,overlapping_platform_claims,overlapping_platform_revenue_claims_cents,limitation,source_class
0,2026-05-04,14,833986,713988,14,0,13,773987,platform claims can overlap; not additive sale...,derived_result
1,2026-05-05,14,887985,773987,14,0,17,1067982,platform claims can overlap; not additive sale...,derived_result
2,2026-05-06,14,839986,719988,14,0,17,1019983,platform claims can overlap; not additive sale...,derived_result
3,2026-05-07,14,833986,767487,14,0,15,893985,platform claims can overlap; not additive sale...,derived_result
4,2026-05-08,14,839986,719988,14,0,15,899985,platform claims can overlap; not additive sale...,derived_result
5,2026-05-09,5,293995,293995,5,0,6,353994,platform claims can overlap; not additive sale...,derived_result
6,2026-05-10,17,1007983,953984,17,0,17,1007983,platform claims can overlap; not additive sale...,derived_result
7,2026-05-11,16,959984,899985,16,0,21,1259979,platform claims can overlap; not additive sale...,derived_result
8,2026-05-12,13,773987,719988,13,0,13,773987,platform claims can overlap; not additive sale...,derived_result
9,2026-05-13,19,1247979,1067982,19,0,22,1487975,platform claims can overlap; not additive sale...,derived_result

                                                    dtype
report_date                                datetime64[us]
commerce_orders                                     int64
commerce_booked_cents                               int64
commerce_net_cents                                  int64
tracked_orders                                      int64
untracked_orders                                    int64
overlapping_platform_claims                         int64
overlapping_platform_revenue_claims_cents           int64
limitation                                            str
source_class                                          str

### raw

#### `budgets` — 852 rows

,report_date,campaign_id,planned_spend_cents,available_at,source_class
0,2026-04-04,C01,4180,2026-04-04 00:00:00-04:00,user_assumption
1,2026-04-04,C02,5940,2026-04-04 00:00:00-04:00,user_assumption
2,2026-04-04,C03,5060,2026-04-04 00:00:00-04:00,user_assumption
3,2026-04-04,C04,3740,2026-04-04 00:00:00-04:00,user_assumption
4,2026-04-04,C05,3520,2026-04-04 00:00:00-04:00,user_assumption
5,2026-04-04,C06,5000,2026-04-04 00:00:00-04:00,user_assumption
6,2026-04-05,C01,4180,2026-04-04 00:00:00-04:00,user_assumption
7,2026-04-05,C02,5940,2026-04-04 00:00:00-04:00,user_assumption
8,2026-04-05,C03,5060,2026-04-04 00:00:00-04:00,user_assumption
9,2026-04-05,C04,3740,2026-04-04 00:00:00-04:00,user_assumption

                                                dtype
report_date                            datetime64[us]
campaign_id                                       str
planned_spend_cents                             int64
available_at         datetime64[us, America/New_York]
source_class                                      str

#### `campaigns` — 6 rows

,campaign_id,channel,objective,click_window_days,source_class
0,C01,google,branded_search,30,synthetic_observation
1,C02,google,nonbranded_search,30,synthetic_observation
2,C03,google,shopping,30,synthetic_observation
3,C04,meta,prospecting,7,synthetic_observation
4,C05,meta,retargeting,7,synthetic_observation
5,C06,affiliate,partner,30,synthetic_observation

                   dtype
campaign_id          str
channel              str
objective            str
click_window_days  int32
source_class         str

#### `costs` — 152 rows

,cost_date,sku,unit_cost_cents,available_at,source_class
0,2026-04-04,ES601,27000,2026-04-04 00:00:00-04:00,user_assumption
1,2026-04-05,ES601,27000,2026-04-05 00:00:00-04:00,user_assumption
2,2026-04-06,ES601,27000,2026-04-06 00:00:00-04:00,user_assumption
3,2026-04-07,ES601,27000,2026-04-07 00:00:00-04:00,user_assumption
4,2026-04-08,ES601,27000,2026-04-08 00:00:00-04:00,user_assumption
5,2026-04-09,ES601,27000,2026-04-09 00:00:00-04:00,user_assumption
6,2026-04-10,ES601,27000,2026-04-10 00:00:00-04:00,user_assumption
7,2026-04-11,ES601,27000,2026-04-11 00:00:00-04:00,user_assumption
8,2026-04-12,ES601,27000,2026-04-12 00:00:00-04:00,user_assumption
9,2026-04-13,ES601,27000,2026-04-13 00:00:00-04:00,user_assumption

                                            dtype
cost_date                          datetime64[us]
sku                                           str
unit_cost_cents                             int64
available_at     datetime64[us, America/New_York]
source_class                                  str

#### `creatives` — 12 rows

    ad_id campaign_id          message format           source_class
0  C01-A0         C01   guided brewing   demo  synthetic_observation
1  C01-A1         C01  at-home routine   demo  synthetic_observation
2  C02-A0         C02   guided brewing   demo  synthetic_observation
3  C02-A1         C02  at-home routine   demo  synthetic_observation
4  C03-A0         C03   guided brewing   demo  synthetic_observation
5  C03-A1         C03  at-home routine   demo  synthetic_observation
6  C04-A0         C04   guided brewing   demo  synthetic_observation
7  C04-A1         C04  at-home routine   demo  synthetic_observation
8  C05-A0         C05   guided brewing   demo  synthetic_observation
9  C05-A1         C05  at-home routine   demo  synthetic_observation

             dtype
ad_id          str
campaign_id    str
message        str
format         str
source_class   str

#### `inventory` — 142 rows

,report_date,sku,available_units,available_at,source_class
0,2026-04-04,ES601,98,2026-04-04 00:00:00-04:00,synthetic_observation
1,2026-04-05,ES601,108,2026-04-05 00:00:00-04:00,synthetic_observation
2,2026-04-06,ES601,70,2026-04-06 00:00:00-04:00,synthetic_observation
3,2026-04-07,ES601,171,2026-04-07 00:00:00-04:00,synthetic_observation
4,2026-04-08,ES601,108,2026-04-08 00:00:00-04:00,synthetic_observation
5,2026-04-09,ES601,220,2026-04-09 00:00:00-04:00,synthetic_observation
6,2026-04-10,ES601,96,2026-04-10 00:00:00-04:00,synthetic_observation
7,2026-04-11,ES601,188,2026-04-11 00:00:00-04:00,synthetic_observation
8,2026-04-12,ES601,199,2026-04-12 00:00:00-04:00,synthetic_observation
9,2026-04-13,ES601,178,2026-04-13 00:00:00-04:00,synthetic_observation

                                            dtype
report_date                        datetime64[us]
sku                                           str
available_units                             int32
available_at     datetime64[us, America/New_York]
source_class                                  str

#### `media` — 1,704 rows

,report_date,campaign_id,ad_id,impressions,clicks,spend_cents,available_at,source_class
0,2026-04-04,C01,C01-A0,370,10,1900,2026-04-05 06:00:00-04:00,synthetic_observation
1,2026-04-04,C01,C01-A1,378,7,1330,2026-04-05 06:00:00-04:00,synthetic_observation
2,2026-04-04,C02,C02-A0,432,12,3240,2026-04-05 06:00:00-04:00,synthetic_observation
3,2026-04-04,C02,C02-A1,517,11,2970,2026-04-05 06:00:00-04:00,synthetic_observation
4,2026-04-04,C03,C03-A0,324,12,2760,2026-04-05 06:00:00-04:00,synthetic_observation
5,2026-04-04,C03,C03-A1,216,6,1380,2026-04-05 06:00:00-04:00,synthetic_observation
6,2026-04-04,C04,C04-A0,637,13,2210,2026-04-05 06:00:00-04:00,synthetic_observation
7,2026-04-04,C04,C04-A1,598,13,2210,2026-04-05 06:00:00-04:00,synthetic_observation
8,2026-04-04,C05,C05-A0,555,15,2400,2026-04-05 06:00:00-04:00,synthetic_observation
9,2026-04-04,C05,C05-A1,658,14,2240,2026-04-05 06:00:00-04:00,synthetic_observation

                                         dtype
report_date                     datetime64[us]
campaign_id                                str
ad_id                                      str
impressions                              Int64
clicks                                   int64
spend_cents                              int64
available_at  datetime64[us, America/New_York]
source_class                               str

#### `orders` — 1,862 rows

,order_id,line_id,journey_id,customer_id,sku,purchased_at,available_at,status,quantity,gross_cents,discount_cents,fulfillment_cents,fee_cents,source_class
0,O000001,1,J0000006,U0000006,ES601,2026-04-04 10:23:00-04:00,2026-04-04 10:53:00-04:00,fulfilled,1,59999,0,1700,1770,synthetic_observation
1,O000002,1,J0000007,U0000005,ES601,2026-04-04 16:17:00-04:00,2026-04-04 16:47:00-04:00,fulfilled,1,59999,0,1700,1770,synthetic_observation
2,O000003,1,J0000035,U0000035,ES601,2026-04-04 09:25:00-04:00,2026-04-04 09:55:00-04:00,fulfilled,1,59999,0,1700,1770,synthetic_observation
3,O000004,1,J0000036,U0000036,ES601,2026-04-04 09:05:00-04:00,2026-04-04 09:35:00-04:00,fulfilled,1,59999,0,1700,1770,synthetic_observation
4,O000005,1,J0000049,U0000047,ES601,2026-04-05 15:42:00-04:00,2026-04-05 16:12:00-04:00,fulfilled,1,59999,0,1700,1770,synthetic_observation
5,O000006,1,J0000053,U0000026,ES601,2026-04-05 15:30:00-04:00,2026-04-05 16:00:00-04:00,fulfilled,1,59999,0,1700,1770,synthetic_observation
6,O000007,1,J0000075,U0000023,ES601,2026-04-05 10:47:00-04:00,2026-04-05 11:17:00-04:00,fulfilled,1,59999,6000,1700,1596,synthetic_observation
7,O000008,1,J0000087,U0000087,ES601,2026-04-14 11:19:00-04:00,2026-04-14 11:49:00-04:00,fulfilled,1,59999,0,1700,1770,synthetic_observation
8,O000009,1,J0000091,U0000091,ES601,2026-04-04 19:43:00-04:00,2026-04-04 20:13:00-04:00,fulfilled,1,59999,0,1700,1770,synthetic_observation
9,O000010,1,J0000098,U0000098,ES601,2026-04-04 10:55:00-04:00,2026-04-04 11:25:00-04:00,fulfilled,1,59999,0,1700,1770,synthetic_observation

                                              dtype
order_id                                        str
line_id                                         str
journey_id                                      str
customer_id                                     str
sku                                             str
purchased_at       datetime64[us, America/New_York]
available_at       datetime64[us, America/New_York]
status                                          str
quantity                                      int32
gross_cents                                   int64
discount_cents                                int64
fulfillment_cents                             int64
fee_cents                                     int64
source_class                                    str

#### `platform_snapshots` — 2,736 rows

,channel,campaign_id,report_date,snapshot_at,conversions,revenue_cents,date_basis,revenue_basis,source_class
0,affiliate,C06,2026-04-04,2026-04-05 06:00:00-04:00,0,0,purchase_date,net_of_discount_before_refunds,synthetic_observation
1,affiliate,C06,2026-04-04,2026-04-07 06:00:00-04:00,0,0,purchase_date,net_of_discount_before_refunds,synthetic_observation
2,affiliate,C06,2026-04-04,2026-04-11 06:00:00-04:00,0,0,purchase_date,net_of_discount_before_refunds,synthetic_observation
3,affiliate,C06,2026-04-05,2026-04-06 06:00:00-04:00,2,119998,purchase_date,net_of_discount_before_refunds,synthetic_observation
4,affiliate,C06,2026-04-05,2026-04-08 06:00:00-04:00,2,119998,purchase_date,net_of_discount_before_refunds,synthetic_observation
5,affiliate,C06,2026-04-05,2026-04-12 06:00:00-04:00,2,119998,purchase_date,net_of_discount_before_refunds,synthetic_observation
6,affiliate,C06,2026-04-06,2026-04-07 06:00:00-04:00,1,59999,purchase_date,net_of_discount_before_refunds,synthetic_observation
7,affiliate,C06,2026-04-06,2026-04-09 06:00:00-04:00,1,59999,purchase_date,net_of_discount_before_refunds,synthetic_observation
8,affiliate,C06,2026-04-06,2026-04-13 06:00:00-04:00,1,59999,purchase_date,net_of_discount_before_refunds,synthetic_observation
9,affiliate,C06,2026-04-07,2026-04-08 06:00:00-04:00,0,0,purchase_date,net_of_discount_before_refunds,synthetic_observation

                                          dtype
channel                                     str
campaign_id                                 str
report_date                      datetime64[us]
snapshot_at    datetime64[us, America/New_York]
conversions                               int64
revenue_cents                             int64
date_basis                                  str
revenue_basis                               str
source_class                                str

#### `promotions` — 1 rows

,promotion_id,start_date,end_date,discount_cents,available_at,source_class
0,P01,2026-06-08,2026-06-21,8000,2026-04-04 12:00:00-04:00,user_assumption

                                           dtype
promotion_id                                 str
start_date                        datetime64[us]
end_date                          datetime64[us]
discount_cents                             int64
available_at    datetime64[us, America/New_York]
source_class                                 str

#### `purchases` — 1,781 rows

,event_id,session_id,order_id,event_at,available_at,source_class
0,EO000001,S0000006,O000001,2026-04-04 10:23:00-04:00,2026-04-04 12:23:00-04:00,synthetic_observation
1,EO000002,S0000007,O000002,2026-04-04 16:17:00-04:00,2026-04-04 18:17:00-04:00,synthetic_observation
2,EO000003,S0000035,O000003,2026-04-04 09:25:00-04:00,2026-04-04 11:25:00-04:00,synthetic_observation
3,EO000004,S0000036,O000004,2026-04-04 09:05:00-04:00,2026-04-04 11:05:00-04:00,synthetic_observation
4,EO000005,S0000050,O000005,2026-04-05 15:42:00-04:00,2026-04-05 17:42:00-04:00,synthetic_observation
5,EO000006,S0000055,O000006,2026-04-05 15:30:00-04:00,2026-04-05 17:30:00-04:00,synthetic_observation
6,EO000007,S0000078,O000007,2026-04-05 10:47:00-04:00,2026-04-05 12:47:00-04:00,synthetic_observation
7,EO000008,S0000091,O000008,2026-04-14 11:19:00-04:00,2026-04-14 13:19:00-04:00,synthetic_observation
8,EO000009,S0000095,O000009,2026-04-04 19:43:00-04:00,2026-04-04 21:43:00-04:00,synthetic_observation
9,EO000010,S0000102,O000010,2026-04-04 10:55:00-04:00,2026-04-04 12:55:00-04:00,synthetic_observation

                                         dtype
event_id                                   str
session_id                                 str
order_id                                   str
event_at      datetime64[us, America/New_York]
available_at  datetime64[us, America/New_York]
source_class                               str

#### `refunds` — 166 rows

,refund_id,order_id,line_id,event_at,available_at,refund_cents,returned_quantity,recovered_inventory_cents,handling_cents,fee_refund_cents,source_class
0,R00001,O000003,1,2026-05-04 09:25:00-04:00,2026-05-04 14:25:00-04:00,59999,1,21600,1200,0,synthetic_observation
1,R00002,O000005,1,2026-05-10 15:42:00-04:00,2026-05-10 20:42:00-04:00,59999,1,21600,1200,0,synthetic_observation
2,R00003,O000018,1,2026-04-15 11:47:00-04:00,2026-04-15 16:47:00-04:00,53999,1,21600,1200,0,synthetic_observation
3,R00004,O000028,1,2026-05-05 16:40:00-04:00,2026-05-05 21:40:00-04:00,59999,1,21600,1200,0,synthetic_observation
4,R00005,O000044,1,2026-05-10 15:59:00-04:00,2026-05-10 20:59:00-04:00,59999,1,21600,1200,0,synthetic_observation
5,R00006,O000058,1,2026-04-23 16:05:00-04:00,2026-04-23 21:05:00-04:00,59999,1,21600,1200,0,synthetic_observation
6,R00007,O000072,1,2026-05-10 14:01:00-04:00,2026-05-10 19:01:00-04:00,59999,1,21600,1200,0,synthetic_observation
7,R00008,O000087,1,2026-05-01 09:46:00-04:00,2026-05-01 14:46:00-04:00,59999,1,21600,1200,0,synthetic_observation
8,R00009,O000095,1,2026-04-28 16:06:00-04:00,2026-04-28 21:06:00-04:00,59999,1,21600,1200,0,synthetic_observation
9,R00010,O000097,1,2026-05-10 09:14:00-04:00,2026-05-10 14:14:00-04:00,59999,1,21600,1200,0,synthetic_observation

                                                      dtype
refund_id                                               str
order_id                                                str
line_id                                                 str
event_at                   datetime64[us, America/New_York]
available_at               datetime64[us, America/New_York]
refund_cents                                          int64
returned_quantity                                     int32
recovered_inventory_cents                             int64
handling_cents                                        int64
fee_refund_cents                                      int64
source_class                                            str

#### `sessions` — 25,034 rows

,session_id,journey_id,customer_id,campaign_id,ad_id,event_at,available_at,source_class
0,S0000001,J0000001,U0000001,C01,C01-A0,2026-04-04 19:17:00-04:00,2026-04-04 20:17:00-04:00,synthetic_observation
1,S0000002,J0000002,U0000002,C01,C01-A0,2026-04-04 18:47:00-04:00,2026-04-04 19:47:00-04:00,synthetic_observation
2,S0000003,J0000003,U0000001,C01,C01-A0,2026-04-04 11:14:00-04:00,2026-04-04 12:14:00-04:00,synthetic_observation
3,S0000004,J0000004,U0000004,C01,C01-A1,2026-04-04 19:34:00-04:00,2026-04-04 20:34:00-04:00,synthetic_observation
4,S0000005,J0000005,U0000005,C01,C01-A0,2026-04-04 08:48:00-04:00,2026-04-04 09:48:00-04:00,synthetic_observation
5,S0000006,J0000006,U0000006,C01,C01-A1,2026-04-04 10:13:00-04:00,2026-04-04 11:13:00-04:00,synthetic_observation
6,S0000007,J0000007,U0000005,C01,C01-A1,2026-04-04 16:07:00-04:00,2026-04-04 17:07:00-04:00,synthetic_observation
7,S0000008,J0000008,U0000001,C01,C01-A0,2026-04-04 08:42:00-04:00,2026-04-04 09:42:00-04:00,synthetic_observation
8,S0000009,J0000009,U0000009,C01,C01-A0,2026-04-04 11:55:00-04:00,2026-04-04 12:55:00-04:00,synthetic_observation
9,S0000010,J0000010,U0000010,C01,C01-A1,2026-04-04 13:10:00-04:00,2026-04-04 14:10:00-04:00,synthetic_observation

                                         dtype
session_id                                 str
journey_id                                 str
customer_id                                str
campaign_id                                str
ad_id                                      str
event_at      datetime64[us, America/New_York]
available_at  datetime64[us, America/New_York]
source_class                               str